name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # or 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /dot_guide_pano/
          webRenderer: canvaskit
